Repository lindsay-terry/whats-for-dinner, pull requests merged in 2024-05, with the labels that each got.

#65 began rendering meal cards
  assets/js/script.js
  index.html
Labels: enhancement

#66 adjusted hover in footer to match theme and added border radius to buttons
  assets/css/style.css
  index.html
Labels: enhancement

#69 Added Styling for Meal Card
  assets/js/script.js
  index.html
Labels: bug

#82 Added comments for CSS
  assets/css/style.css
Labels: documentation
